---
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "pyink"
    open-pull-requests-limit: 1
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: python
        versions:
          - 3.11.0b1-slim-bullseye
    open-pull-requests-limit: 1
  - package-ecosystem: docker
    directory: "/postgres"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "postgres"
        update-types:
          - "version-update:semver-major"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
